### ISSUE TITLE
request option to show:  description allway / title only if truncated 

### ISSUE THREAD

**Issue by melomane63** [RaphaelRochet/applications-overview-tooltip#13]
It is redundant to show title if it is not truncated, and we have options for this.
but this stop to show description of application.

My request is the optional possibility to
allway show description
and
show title only if it is truncated

**Comment by RaphaelRochet** [comment]
Seems legit :+1:

**Comment by RaphaelRochet** [comment]
That is now possibles ! you can try latest master version :) ( done in 1f7d1ad )

**Comment by melomane63** [comment]
ok, work fine. very good!
