### ISSUE TITLE
applications-overview-tooltip-8 breaks with gnome-shell-3.34

### ISSUE THREAD

**Issue by pacho2** [RaphaelRochet/applications-overview-tooltip#14]
As soon as I have updated to v8 from v7 and restart gnome-shell I lose the tooltips. I have reviewed the commits and this looks to be the culprit
https://github.com/RaphaelRochet/applications-overview-tooltip/commit/e7bfef9a620af2335ee0934b480e751b24fe223c

If I reverse it, tooltips are shown again

Thanks a lot!

**Comment by RaphaelRochet** [comment]
Hi,
How/why did you update ?

v8 was not meant for gnome 3.34, in metadata there is only "3.36"

**Comment by pacho2** [comment]
Oh, I installed it manuallly

I don't know why tweaks and https://extensions.gnome.org/local/ shows it as properly loaded :/

But I see metadata is correct forcing 3.36 yes

Sorry for the noise

**Comment by RaphaelRochet** [comment]
No worried. Just wondering ;)
