### ISSUE TITLE
Tooltip stays on screen even out of application search results

### ISSUE THREAD

**Issue by Magean0** [RaphaelRochet/applications-overview-tooltip#15]
Hello,

Thanks for this extension, it's a must have for usability, in particular as long as the app grid keeps truncating application titles.

I noticed a minor bug:

-open the Activities overview
-type to search an application
-hover your mouse over the application icon for the tooltip to show
-then press Escape to exit the Overview
-notice that the [tooltip remains on screen](https://imgur.com/cKO8gyu) even out of the overview
-the only way to get rid of it is to show another application tooltip

Overall, this means that you should not exit the overview while a tooltip is being displayed on a search result.

I haven't encountered this bug when hovering over icons in the app grid - as opposed to search results.

Thanks for having a look.

EDIT: fixed imgur link.

**Comment by RaphaelRochet** [comment]
Hi,
Can you try last master version ( 2bd05bc should fix this ) ?

**Comment by Magean0** [comment]
It's apparently fixed indeed. Well done and thanks for your responsiveness!

**Comment by pacho2** [comment]
Could a new version including this fix be released?

Thanks

**Comment by RaphaelRochet** [comment]
Oh, sorry I forgot it. Sure will release a new version soon. Thanks for the reminder :+1:

**Comment by RaphaelRochet** [comment]
And that is now done. Submitted to extensions.gnome.org and waiting for review.

**Comment by pacho2** [comment]
Thanks!
