### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by esa1975** [RaphaelRochet/applications-overview-tooltip#16]
Not an issue but I just wanted to say thank you for this. For as much as I enjoy using GNOME, their application screen leaves much to be desired. I have a number of applications with similar names and icons and it's difficult to discern which is the correct one because the name is cut off. This completely solves that issue. I really appreciate you taking the time to make this.

**Comment by RaphaelRochet** [comment]
Thanks ;)
To be honest I did not make it, I only make it live longer. Original author is @fbianconi , and @karlitos added some features. 
I also think that sometimes it's helpful to have the full name of the application :+1:
