### ISSUE TITLE
Ubuntu 20.04 error install.

### ISSUE THREAD

**Issue by kred-jon** [RaphaelRochet/applications-overview-tooltip#17]
Hello,
Previously using it on 18 and 19 version of Ubuntu work well. However at 20.04 installation is error.

OS: Ubuntu 20.04
GNOME Shell: 3.36.4

Thanks.

**Comment by RaphaelRochet** [comment]
Hi,
I downloaded a fresh Fedora 32 and updated it, and then installed the extensions with no problem.
I am downloading Ubunto 20.04.1 to try also.

Did you try deleting the extension and reinstalling ?

**Comment by RaphaelRochet** [comment]
Okay, that's annoying, I have downloaded latest Ubuntu 20.04.1, fully updated it, but everything is ok.

![image](https://user-images.githubusercontent.com/1675389/91022434-80456080-e5f5-11ea-9e7d-c97a1d0311a5.png)

I will need more info to debug this ...

Can you try this command and paste the result if any ? (Do it after you get the error)
```
journalctl -b GNOME_SHELL_EXTENSION_UUID=applications-overview-tooltip@RaphaelRochet
```

**Comment by kred-jon** [comment]
![image](https://user-images.githubusercontent.com/38023611/91024147-1a270080-e62a-11ea-9d08-bab78f65c1a4.png)
Now it's OK, however when received an update. Update it then will failed again.

**Comment by kred-jon** [comment]
Will keep it monitor and will paste the log if it happen again. Thanks.
