### ISSUE TITLE
Hovering over the "Settings" app makes tooltip disappear for all apps

### ISSUE THREAD

**Issue by Gefrierbrand** [RaphaelRochet/applications-overview-tooltip#2]
Steps to reproduce:
1. Hover over an app in the overview -> Extension works as expected
2. Move cursor over "Settings" system-app -> Tooltip vanishes, name is still displayed
3. Hover over first app again -> no tooltip

if move mouse out of the way of all apps and wait a few sec an then return to any app but "Settings", the tooltips work again for those.

I've made a small screencast showing the problem in action:
[bug.webm.zip](https://github.com/RaphaelRochet/applications-overview-tooltip/files/249485/bug.webm.zip)

**Comment by RaphaelRochet** [comment]
Thanks for your report. I think I found the bug. Please try the latest github version and tell me if it's fixed for you too.

**Comment by Gefrierbrand** [comment]
This fixed the issue, thank you.
