### ISSUE TITLE
tooltips not appearing on search results

### ISSUE THREAD

**Issue by briaguya-ai** [RaphaelRochet/applications-overview-tooltip#20]
env:
debian bullseye/sid
GNOME Shell 3.38.2

tooltips are working perfectly in the main "Show Applications" menu, but do not appear to be connected to the search results

i wasn't sure if this should be a bug or a feature request, but this line makes me think it's a bug
https://github.com/RaphaelRochet/applications-overview-tooltip/blob/2e81270c728f421f915900cab2725a8e20c87b0a/extension.js#L60

**Comment by RaphaelRochet** [comment]
Indeed it used to.
I'll have a look and try to fix it ... or edit the comment

**Comment by RaphaelRochet** [comment]
As expected, is was a change in 3.38.

![image](https://user-images.githubusercontent.com/1675389/106262213-fb551780-6222-11eb-824a-09af8d0b8826.png)

I got it working. Can you test the latest master ?

**Comment by briaguya-ai** [comment]
just tested the latest out! it works! thanks!

**Comment by hmaarrfk** [comment]
nice. Excited for a release!

**Comment by RaphaelRochet** [comment]
Damned, I have not released it yet. I will do ASAP, sorry for that.

**Comment by RaphaelRochet** [comment]
That is now done !
I have submitted it to extensions.gnome.org, it's waiting for review !
