### ISSUE TITLE
metadata.json: given filename for "settings-schema" is different from the actual filename

### ISSUE THREAD

**Issue by doppelhelix** [RaphaelRochet/applications-overview-tooltip#21]
metadata.json:
**`"settings-schema": "org.gnome.shell.extensions.applications-overview-tooltip"`**
actual filename:
**`org.gnome.shell.extensions.appoverviewtooltip.gschema.xml`**

probably not important, since the extension works just fine.  But parsing the metadata.json  does not give the expected result.

**Comment by RaphaelRochet** [comment]
Whats's important is the schema id inside the source XML. It ens up in a "gschemas.compiled" file anyways.
But hey can't hurt to name things well. I renamed it :+1: Thanks.

**Comment by doppelhelix** [comment]
Thank you. It was really just a minor inconvenience on arch-linux. It seems that the general practice for building extension packages is to copy the provided xml to  `/usr/share/glib-2.0/schemas/` and let  `glib-compile-schemas` regenerate the systemwide gschema.
Parsing the metadata.json makes it easier to maintain the PKGBUILD than to hardcode the filename.
