### ISSUE TITLE
GNOME Shell 40 [Request for comments]

### ISSUE THREAD

**Issue by RaphaelRochet** [RaphaelRochet/applications-overview-tooltip#23]
GNOME Shell 40 is different, and show full application name on hover by default.
I wonder if this extension is still useful ?

**Comment by Tuxman2** [comment]
Hi,

yes, your extension is still useful because we have the description of the application under his name. As there are a lot of applications, we don't know what they are used for. So for the beginner user under Gnu/Linux, it is something that can help him.

Regards.

**Comment by melomane63** [comment]
Hello, yes it can be usefull, as tuxman2 as explayned.

**Comment by eMorph** [comment]
Having something to display the description of the app would be nice tbh

**Comment by RaphaelRochet** [comment]
Okay. That's enough positive feedback for me to have a try on porting to 40.x :+1:

**Comment by Tuxman2** [comment]
@RaphaelRochet: Thanks. ;-)

**Comment by RaphaelRochet** [comment]
I still have a few issues and the prefs window to fix but ...
![image](https://user-images.githubusercontent.com/1675389/118824203-f2638100-b8b9-11eb-8faf-ad5b65a96b2f.png)
It's on its way  :)

**Comment by RaphaelRochet** [comment]
Release is done. You can wait for review on extensions.gnome.org or download from GitHub :)
