### ISSUE TITLE
Support for Gnome 41

### ISSUE THREAD

**Issue by Tuxman2** [RaphaelRochet/applications-overview-tooltip#25]
Hello,

can you add support for Gnome 41 ?

Thanks.

**Comment by RaphaelRochet** [comment]
I do not have Gnome 41 yet (I'm on Arch). What distro do you use to have Gnome 41 ?

**Comment by rastersoft** [comment]
I have Gnome 41 in Debian Sid and tried to just add "41" to metadata.json, and it works fine.

**Comment by RaphaelRochet** [comment]
I do not have gnome 41 yet, but I published it on EGO anyway based on your feedback ;)
