### ISSUE TITLE
[Feature Request] Add GNOME 45 Support

### ISSUE THREAD

**Issue by git-Hmmm** [RaphaelRochet/applications-overview-tooltip#30]
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

check: [gjs.guide/extensions/upgrading/gnome-shell-45.html](https://gjs.guide/extensions/upgrading/gnome-shell-45.html)

**Comment by Tuxman2** [comment]
Hello,

I'm using your extension and it is very usefull. I understand your are tired that the Gnome team change the support of Gnome extensions  with each major release. Unfortunately, we cannot change this. We just have to adapt or stop using Gnome. I see that a lot of Gnome extensions make the change each time there is a new major version of Gnome. It's just a matter of will, but I understand your point of view.

Many thanks for your work.

**Comment by RaphaelRochet** [comment]
I had help on another extension, maybe I can make this one work again ...

**Comment by Tuxman2** [comment]
Hello,

an idea when it will be available ?

Thanks.

**Comment by RaphaelRochet** [comment]
Had quite a hard time even starting to work on it ... and forgot about it. I'll try to find time for it ...

**Comment by RaphaelRochet** [comment]
And ... done ! I hope I did it right, seems to be working though ...

Could you try from last commit ?

**Comment by Tuxman2** [comment]
Hello,

thank you very much for your work. ;-)

I will test it this weekend and I will tell you if it is ok.

Regards.

**Comment by Tuxman2** [comment]
@RaphaelRochet: Hello,

I tested on Fedora 39 with Gnome 45.x and it works very well (last commit) :+1: 

Thank you very much to port this extension on Gnome 45. :1st_place_medal: 

Very happy to use applications-overview-tooltip again. :-)

Regards.

**Comment by RaphaelRochet** [comment]
Great. I have submitted it to extensions.gnome.org for review.
