### ISSUE TITLE
Port to GNOME 47

### ISSUE THREAD

**Issue by antrmn** [RaphaelRochet/applications-overview-tooltip#31]
GNOME 47.rc has been released, with the stable release set for September 18. Please update for GNOME 47 compatibility. The upgrade guide can be found here: [Port Extensions to GNOME Shell 47](https://gjs.guide/extensions/upgrading/gnome-shell-47.html).

Thanks!

**Comment by RaphaelRochet** [comment]
Should already be compatible. Have you tested ?
(I've tested on beta last month)

**Comment by antrmn** [comment]
I didn't, but since GNOME 47 brought so few changes in the ""API"" compared to 45 and 46 I'm not too surpired. I guess a metadata change would suffice
