### ISSUE TITLE
No tooltip inside groups

### ISSUE THREAD

**Issue by shiba89** [RaphaelRochet/applications-overview-tooltip#5]
Very cool extension, but (for me?) it doesn't work for items inside expanded groups.

**Comment by RaphaelRochet** [comment]
It works for me. Are you using gnome-shell 3.20 ? Did you install from extensions.gnome.org ?
Can you post a screenshot of your settings ?

**Comment by shiba89** [comment]
What actually happens is that it stops working for expanded groups after my PC is running for a few hours, I just discovered that. Restarting the shell solves the problem

![schermata del 2016-06-01 11-27-08](https://cloud.githubusercontent.com/assets/3816409/15704621/ce8d45ae-27eb-11e6-9c8e-410e02a378ab.png)

Installed from extensions.gnome.org on GNOME Shell 3.20.2 (Gentoo).

**Comment by RaphaelRochet** [comment]
Seems this bug will be difficult to hunt !
If you know how, can you check gnome-shell logs for any error when such tooltip doesn't show ?

**Comment by mirandir** [comment]
Hello,

I can confirm the problem. Here is how I reproduce it (with Gnome 3.20.2):
- start or restart Gnome Shell -> the extension works inside groups
- lock the session with Windows + L
- unlock the session by taping your password
-> the extension doesn't works anymore inside groups.

**Comment by RaphaelRochet** [comment]
Thanks @mirandir I was able to reproduce this. I'll try to hunt this bug down soon.

**Comment by RaphaelRochet** [comment]
Now fixed ;)

**Comment by mirandir** [comment]
Thanks!

**Comment by shiba89** [comment]
I'm sorry I couldn't help you (not having much free time), but I confirm this is fixed for me too. Thank you very much :)
