### ISSUE TITLE
Tooltip does not show up when I hover over two icons with long names in sequence

### ISSUE THREAD

**Issue by glaubersm** [RaphaelRochet/applications-overview-tooltip#6]
Hi

I use your extension on Arch Linux running Gnome 3.30.2 under Wayland. Title says by itself, 
watch my screencast please. Tooltip shows up when I hover over "New application" 
but it does not when I hover the icon above "New application",

https://youtu.be/d51Z4KVd_7I

**Comment by RaphaelRochet** [comment]
Can you post your extension settings ?
Seems your application list is not vanilla, do you have any other extension that tempers with this display ?
If you enable only applications-overview-tooltip extension in GNOME, does the bug still exist ?

**Comment by glaubersm** [comment]
I use several shell extensions. The bug described here occurs even when only applications-overview-tooltip extension is enabled. The following screenshot shows my settings.

![extension](https://user-images.githubusercontent.com/15967631/52541372-46966700-2d7b-11e9-8752-b95f0b768c5d.png)

**Comment by RaphaelRochet** [comment]
Thanks. I am able to reproduce the bug. Working on a fix.

**Comment by RaphaelRochet** [comment]
Should be fixed with last commit. Can you test ?

**Comment by glaubersm** [comment]
It's fixed! Thank you very much Raphael.
Have a nice day.
